apiVersion: v1
kind: Service
metadata:
  name: cost-analyzer
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: cost-analyzer
  ports:
    - port: 80
      targetPort: 9001
