apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: oauth2-proxy
  ports:
    - port: 80
      targetPort: 4180
